spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ead8e7984fdc096a6e450e0a638a8c8d
            client-secret: 2lTkLrlaOjZWAGJ0PkhNVzWEBGk9HI3E
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 20835971511-s98vnl14ku6ev20g8rq704d1jdf7jro7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: jwt
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://accounter-rds.clcywhhrzlxo.ap-northeast-2.rds.amazonaws.com:3306/accounter?useSSL=false&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: admin
    password: rkdduddms11
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379